name: MonadAssistant
options:
  bundleIdPrefix: com.monad
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

packages:
  OpenAI:
    url: https://github.com/MacPaw/OpenAI.git
    branch: main
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 7.0.0

settings:
  base:
    SWIFT_VERSION: "6.0"
    marketing_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: YES
  debug:
    ENABLE_HARDENED_RUNTIME: NO
    CODE_SIGN_IDENTITY: "-"
  release:
    ENABLE_HARDENED_RUNTIME: YES

targets:
  # Core Logic - macOS
  MonadCore:
    type: framework
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadCore
        excludes:
          - "**/.DS_Store"
    dependencies:
      - sdk: NaturalLanguage.framework
      - package: OpenAI
        product: OpenAI
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_NAME: MonadCore
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.core
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES

  # Core Logic - iOS
  MonadCore-iOS:
    type: framework
    platform: iOS
    deploymentTarget:
      iOS: "17.0"
    sources:
      - path: Sources/MonadCore
        excludes:
          - "**/.DS_Store"
    dependencies:
      - sdk: NaturalLanguage.framework
      - package: OpenAI
        product: OpenAI
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_NAME: MonadCore
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.core.ios
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES

  # UI - macOS
  MonadUI:
    type: framework
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadUI
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: MonadCore
      - package: OpenAI
        product: OpenAI
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_NAME: MonadUI
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.ui
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES
        SWIFT_EMIT_LOC_STRINGS: YES

  # UI - iOS
  MonadUI-iOS:
    type: framework
    platform: iOS
    deploymentTarget:
      iOS: "17.0"
    sources:
      - path: Sources/MonadUI
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: MonadCore-iOS
      - package: OpenAI
        product: OpenAI
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_NAME: MonadUI
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.ui.ios
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES
        SWIFT_EMIT_LOC_STRINGS: YES

  # Model Context Protocol - macOS Only
  MonadMCP:
    type: framework
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadMCP
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: MonadCore
    settings:
      base:
        PRODUCT_NAME: MonadMCP
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.mcp
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES

  # Main Application - macOS
  MonadAssistant:
    type: application
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadAssistant-macOS
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: MonadCore
      - target: MonadUI
      - target: MonadMCP
    settings:
      base:
        PRODUCT_NAME: MonadAssistant
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.assistant
        INFOPLIST_FILE: Sources/MonadAssistant-macOS/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: Monad Assistant
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "ENABLE_MCP"
      debug:
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
      release:
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        CODE_SIGN_ENTITLEMENTS: Sources/MonadAssistant-macOS/MonadAssistant.entitlements
        CODE_SIGN_STYLE: Automatic

  # Main Application - iOS
  MonadAssistant-iOS:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: "17.0"
    sources:
      - path: Sources/MonadAssistant-iOS
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: MonadCore-iOS
      - target: MonadUI-iOS
    settings:
      base:
        PRODUCT_NAME: MonadAssistant
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.assistant.ios
        INFOPLIST_FILE: Sources/MonadAssistant-iOS/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: Monad
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        TARGETED_DEVICE_FAMILY: "1,2"
      debug:
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
      release:
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        CODE_SIGN_STYLE: Automatic

  # Core Logic Tests
  MonadCoreTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Tests/MonadCoreTests
    dependencies:
      - target: MonadCore
      - target: MonadUI
      - package: OpenAI
        product: OpenAI
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.core-tests
        CODE_SIGNING_ALLOWED: NO
      debug:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic

  # MCP Tests
  MonadMCPTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Tests/MonadMCPTests
    dependencies:
      - target: MonadMCP
      - target: MonadCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.mcp-tests
        CODE_SIGNING_ALLOWED: NO
      debug:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic

schemes:
  MonadAssistant:
    build:
      targets:
        MonadAssistant: all
        MonadUI: all
        MonadCore: all
        MonadMCP: all
    test:
      targets:
        - MonadCoreTests
        - MonadMCPTests
    run:
      executable: MonadAssistant
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  MonadAssistant-iOS:
    build:
      targets:
        MonadAssistant-iOS: all
        MonadUI-iOS: all
        MonadCore-iOS: all
    run:
      executable: MonadAssistant-iOS
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release