name: MonadAssistant
options:
  bundleIdPrefix: com.monad
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

packages:
  OpenAI:
    url: https://github.com/MacPaw/OpenAI.git
    branch: main
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 7.0.0

settings:
  base:
    SWIFT_VERSION: "6.0"
    marketing_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: YES
  debug:
    ENABLE_HARDENED_RUNTIME: NO
    CODE_SIGN_IDENTITY: "-"
  release:
    ENABLE_HARDENED_RUNTIME: YES

targets:
  # Core Pure Logic - Cross Platform (macOS, iOS, Linux compatible)
  MonadCore:
    type: framework
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadCore
    dependencies:
      - package: OpenAI
        product: OpenAI
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_NAME: MonadCore
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.core
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES

  # Core Shared UI & Glue - macOS
  Shared:
    type: framework
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/Shared
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: MonadCore
      - package: OpenAI
        product: OpenAI
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_NAME: Shared
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.shared
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES
        SWIFT_EMIT_LOC_STRINGS: YES

  # Core Shared UI & Glue - iOS
  Shared-iOS:
    type: framework
    platform: iOS
    deploymentTarget:
      iOS: "17.0"
    sources:
      - path: Sources/Shared
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: MonadCore
      - package: OpenAI
        product: OpenAI
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_NAME: Shared
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.shared.ios
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES
        SWIFT_EMIT_LOC_STRINGS: YES

  # Model Context Protocol - macOS Only
  MonadMCP:
    type: framework
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadMCP
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: MonadCore
    settings:
      base:
        PRODUCT_NAME: MonadMCP
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.mcp
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES

  # Main Application - macOS
  MonadAssistant:
    type: application
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadAssistant-macOS
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Shared
      - target: MonadMCP
      - target: MonadCore
    settings:
      base:
        PRODUCT_NAME: MonadAssistant
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.assistant
        INFOPLIST_KEY_CFBundleDisplayName: Monad Assistant
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_NSHumanReadableCopyright: Copyright © 2025 Monad. All rights reserved.
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "ENABLE_MCP"
      debug:
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
      release:
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        CODE_SIGN_ENTITLEMENTS: Sources/MonadAssistant-macOS/MonadAssistant.entitlements
        CODE_SIGN_STYLE: Automatic

  # Main Application - iOS
  MonadAssistant-iOS:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: "17.0"
    sources:
      - path: Sources/MonadAssistant-iOS
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Shared-iOS
      - target: MonadCore
    settings:
      base:
        PRODUCT_NAME: MonadAssistant
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.assistant.ios
        INFOPLIST_KEY_CFBundleDisplayName: Monad
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        TARGETED_DEVICE_FAMILY: "1,2"
      debug:
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
      release:
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        CODE_SIGN_STYLE: Automatic

  # Unit Tests (Mostly testing Shared)
  MonadAssistantTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Tests/MonadAssistantTests
    dependencies:
      - target: Shared
      - target: MonadMCP
      - target: MonadCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.assistant-tests

schemes:
  MonadAssistant:
    build:
      targets:
        MonadAssistant: all
        Shared: all
        MonadMCP: all
        MonadCore: all
    test:
      targets:
        - MonadAssistantTests
    run:
      executable: MonadAssistant
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  MonadAssistant-iOS:
    build:
      targets:
        MonadAssistant-iOS: all
        Shared-iOS: all
        MonadCore: all
    run:
      executable: MonadAssistant-iOS
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
