name: MonadProject
options:
  bundleIdPrefix: com.monad
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

packages:
  OpenAI:
    url: https://github.com/MacPaw/OpenAI.git
    branch: main
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 7.0.0
  Hummingbird:
    url: https://github.com/hummingbird-project/hummingbird.git
    from: 2.0.0
  ArgumentParser:
    url: https://github.com/apple/swift-argument-parser.git
    from: 1.3.0

settings:
  base:
    SWIFT_VERSION: "6.0"
    marketing_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: YES
  debug:
    ENABLE_HARDENED_RUNTIME: NO
    CODE_SIGN_IDENTITY: "-"
  release:
    ENABLE_HARDENED_RUNTIME: YES

targets:
  # Core Logic
  MonadCore:
    type: framework
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadCore
        excludes:
          - "**/.DS_Store"
    dependencies:
      - sdk: NaturalLanguage.framework
      - package: OpenAI
        product: OpenAI
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_NAME: MonadCore
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.core
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES

  # Monad Server Core
  MonadServerCore:
    type: framework
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadServerCore
    dependencies:
      - package: Hummingbird
        product: Hummingbird
      - target: MonadCore
    settings:
      base:
        PRODUCT_NAME: MonadServerCore
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.server.core
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES

  # Monad Server (REST API)
  MonadServer:
    type: tool
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadServer
    dependencies:
      - package: Hummingbird
        product: Hummingbird
      - package: ArgumentParser
        product: ArgumentParser
      - target: MonadCore
      - target: MonadServerCore
    settings:
      base:
        PRODUCT_NAME: MonadServer
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.server

  # HTTP Client Library
  MonadClient:
    type: framework
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadClient
    settings:
      base:
        PRODUCT_NAME: MonadClient
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.client
        SKIP_INSTALL: YES
        INSTALL_PATH: "@rpath"
        DEFINES_MODULE: YES

  # CLI Application
  MonadCLI:
    type: tool
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Sources/MonadCLI
    dependencies:
      - package: ArgumentParser
        product: ArgumentParser
      - target: MonadClient
    settings:
      base:
        PRODUCT_NAME: monad
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.cli

  # Core Logic Tests
  MonadCoreTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Tests/MonadCoreTests
    dependencies:
      - target: MonadCore
      - package: OpenAI
        product: OpenAI
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.monad.core-tests
        CODE_SIGNING_ALLOWED: NO
      debug:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic

  # MonadServerTests
  MonadServerTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget:
      macOS: "14.0"
    sources:
      - path: Tests/MonadServerTests
    dependencies:
      - package: Hummingbird
        product: Hummingbird
      - package: Hummingbird
        product: HummingbirdTesting
      - target: MonadCore
      - target: MonadServerCore

schemes:
  MonadServer:
    build:
      targets:
        MonadServer: all
        MonadServerCore: all
        MonadCore: all
    test:
      targets:
        - MonadCoreTests
        - MonadServerTests
    run:
      executable: MonadServer
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  MonadCLI:
    build:
      targets:
        MonadCLI: all
        MonadClient: all
    run:
      executable: MonadCLI
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release